# Generated by Django 5.2 on 2025-04-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_alter_user_country_code_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='blog_api.countries'),
        ),
    ]
