# Generated by Django 5.1.6 on 2025-04-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_alter_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_code', to='blog_api.countries'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='blog_api.user')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countrycode', to='blog_api.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='blog_api.user')),
            ],
        ),
    ]
