# Generated by Django 5.1.6 on 2025-04-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0007_alter_user_country_code_alter_user_email_merchants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='blog_api.order')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('merchants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to='blog_api.merchants')),
            ],
        ),
    ]
